// <auto-generated />
namespace ninetyFourPercent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tablefix2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablefix2));
        
        string IMigrationMetadata.Id
        {
            get { return "201903130028052_table-fix-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
